
2022-01-25 06:44:46,710:__main__:
Filename: Purchase Order 4500634027 from Allied Pinnacle Pty.pdf. Error occured in NLP flow module.
Traceback (most recent call last):
  File "/data/BNSF/bnsf_solution/apps/start_exacto.py", line 320, in __single_doc_process
    sta, dyn,config_id = drive_nlp_flow(os.path.splitext(document_path)[0], text_files_path, custom_extractor_obj, user=self.user_id, config=self.config_id)
  File "/data/BNSF/bnsf_solution/apps/exacto_extraction_flow.py", line 90, in drive_nlp_flow
    info_folder_path = egut.create_output_folder(text_files_path)
  File "/data/BNSF/bnsf_solution/apps/exacto_general_utils.py", line 120, in create_output_folder
    info_folder_path = os.path.join(text_files_path, "outputs")
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
