
2022-02-02 10:03:21,338:__main__:
Filename: 0005110974.PDF. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 549, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/bc251ca7/test/0005110974.PDF/outputs/Table_txt'

2022-02-02 10:03:41,567:__main__:
Filename: 0005110974.PDF. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 549, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/bc251ca7/test/0005110974.PDF/outputs/Table_txt'
