
2023-08-31 12:48:06,403:__main__:
Filename: abc.pdf. Error occured in NLP flow module.
Traceback (most recent call last):
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/start_exacto.py", line 563, in __single_doc_process
    sta, dyn,config_id = drive_nlp_flow(os.path.splitext(document_path)[0], text_files_path, custom_extractor_obj, user=self.user_id, config=self.config_id)
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/exacto_extraction_flow.py", line 131, in drive_nlp_flow
    custom_field_dict = custom_extractor_obj.extract_custom_fields()
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/ExtractCustomFields/CustomFieldsExtractor.py", line 119, in extract_custom_fields
    for base_fname in self.pattern_files_dict:
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/ExtractCustomFields/CustomFieldsExtractor.py", line 45, in pattern_files_dict
    for file in os.listdir(self.pattern_folderpath):
FileNotFoundError: [Errno 2] No such file or directory: '/datadrive/unzip/eips_data/user_active_learning_data/1234/560'

2023-08-31 13:05:28,020:__main__:
Filename: 20E536392v.1.pdf. Error occured in NLP flow module.
Traceback (most recent call last):
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/start_exacto.py", line 563, in __single_doc_process
    sta, dyn,config_id = drive_nlp_flow(os.path.splitext(document_path)[0], text_files_path, custom_extractor_obj, user=self.user_id, config=self.config_id)
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/exacto_extraction_flow.py", line 131, in drive_nlp_flow
    custom_field_dict = custom_extractor_obj.extract_custom_fields()
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/ExtractCustomFields/CustomFieldsExtractor.py", line 119, in extract_custom_fields
    for base_fname in self.pattern_files_dict:
  File "/datadrive/unzip/ips/invoiceProduct_solution/apps/ExtractCustomFields/CustomFieldsExtractor.py", line 45, in pattern_files_dict
    for file in os.listdir(self.pattern_folderpath):
FileNotFoundError: [Errno 2] No such file or directory: '/datadrive/unzip/eips_data/user_active_learning_data/1234/560'
