
2022-03-09 05:23:06,676:__main__:
Filename: R3021002_acceptIT_Simonswerk_Wartung_MDM.pdf. Error occured in ocr module.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 329, in __single_doc_process
    ocr_success, text_files_path, phase, ocr_flag = drive_ocr_flow(esett.OCR_MODEL_PATHS, document_path, output_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/exacto_extraction_flow.py", line 77, in drive_ocr_flow
    return ocr_success, text_files_path, phase, ocr_flag
UnboundLocalError: local variable 'text_files_path' referenced before assignment

2022-03-09 05:24:13,754:__main__:
Filename: R3021002_acceptIT_Simonswerk_Wartung_MDM.pdf. Error occured in ocr module.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 329, in __single_doc_process
    ocr_success, text_files_path, phase, ocr_flag = drive_ocr_flow(esett.OCR_MODEL_PATHS, document_path, output_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/exacto_extraction_flow.py", line 77, in drive_ocr_flow
    return ocr_success, text_files_path, phase, ocr_flag
UnboundLocalError: local variable 'text_files_path' referenced before assignment

2022-03-09 05:37:10,238:__main__:
Filename: R3021002_acceptIT_Simonswerk_Wartung_MDM.pdf. Error occured in ocr module.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 329, in __single_doc_process
    ocr_success, text_files_path, phase, ocr_flag = drive_ocr_flow(esett.OCR_MODEL_PATHS, document_path, output_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/exacto_extraction_flow.py", line 77, in drive_ocr_flow
    return ocr_success, text_files_path, phase, ocr_flag
UnboundLocalError: local variable 'text_files_path' referenced before assignment

2022-03-09 05:37:10,238:__main__:
Filename: R3021002_acceptIT_Simonswerk_Wartung_MDM.pdf. Error occured in ocr module.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 329, in __single_doc_process
    ocr_success, text_files_path, phase, ocr_flag = drive_ocr_flow(esett.OCR_MODEL_PATHS, document_path, output_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/exacto_extraction_flow.py", line 77, in drive_ocr_flow
    return ocr_success, text_files_path, phase, ocr_flag
UnboundLocalError: local variable 'text_files_path' referenced before assignment
